---
deployment:
  tasks:
    # Path untuk project Laravel penuh (bukan public_html)
    - export PROJECTPATH=/home/gerai270/laravel_app
    - export DEPLOYPATH=/home/gerai270/public_html

    # Copy semua file project ke folder project khusus
    - /bin/rsync -av --exclude='.git' --exclude='node_modules' ./ $PROJECTPATH

    # Copy isi folder public Laravel ke public_html
    - /bin/rsync -av $PROJECTPATH/public/ $DEPLOYPATH

    # Masuk ke folder project
    - cd $PROJECTPATH && /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader

    # Set permission
    - chmod -R 775 $PROJECTPATH/storage $PROJECTPATH/bootstrap/cache
    - chown -R $USER:$USER $PROJECTPATH/storage $PROJECTPATH/bootstrap/cache

    # Clear & cache Laravel
    - cd $PROJECTPATH && php artisan config:clear
    - cd $PROJECTPATH && php artisan cache:clear
    - cd $PROJECTPATH && php artisan route:clear
    - cd $PROJECTPATH && php artisan view:clear
    - cd $PROJECTPATH && php artisan config:cache
    - cd $PROJECTPATH && php artisan route:cache
    - cd $PROJECTPATH && php artisan view:cache

    # Buat symlink storage
    - cd $PROJECTPATH && php artisan storage:link
